/* =========================================================
   ★ このファイルは自動生成されます。手で編集しないでください ★

   photos/gourmet/ と photos/sweets/ に写真を追加してコミットすると、
   GitHub Actions がこのファイルを自動で書き換えます。
   （写真を入れるだけでサイトのタブに反映されます）
   ========================================================= */

const SITE_PHOTOS_AUTO = {
  gourmet: [
    { src: "photos/gourmet/01_gourmet_hyogensha_-53.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 001" },
    { src: "photos/gourmet/02_gourmet_hyogensha_-52.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 002" },
    { src: "photos/gourmet/03_gourmet_hyogensha_-2.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 003" },
    { src: "photos/gourmet/04_gourmet_hyogensha_-31.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 004" },
    { src: "photos/gourmet/05_gourmet_hyogensha_-25.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 005" },
    { src: "photos/gourmet/06_gourmet_hyogensha_-70.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 006" },
    { src: "photos/gourmet/07_gourmet_hyogensha_-23.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 007" },
    { src: "photos/gourmet/08_gourmet_hyogensha_-36.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 008" },
    { src: "photos/gourmet/09_gourmet_hyogensha_-55.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 009" },
    { src: "photos/gourmet/10_gourmet_hyogensha_-42.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 010" },
    { src: "photos/gourmet/gourmet_hyogensha_-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 011" },
    { src: "photos/gourmet/gourmet_hyogensha_-10.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 012" },
    { src: "photos/gourmet/gourmet_hyogensha_-11.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 013" },
    { src: "photos/gourmet/gourmet_hyogensha_-12.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 014" },
    { src: "photos/gourmet/gourmet_hyogensha_-13.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 015" },
    { src: "photos/gourmet/gourmet_hyogensha_-14.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 016" },
    { src: "photos/gourmet/gourmet_hyogensha_-15.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 017" },
    { src: "photos/gourmet/gourmet_hyogensha_-16.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 018" },
    { src: "photos/gourmet/gourmet_hyogensha_-17.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 019" },
    { src: "photos/gourmet/gourmet_hyogensha_-18.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 020" },
    { src: "photos/gourmet/gourmet_hyogensha_-19.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 021" },
    { src: "photos/gourmet/gourmet_hyogensha_-20.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 022" },
    { src: "photos/gourmet/gourmet_hyogensha_-21.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 023" },
    { src: "photos/gourmet/gourmet_hyogensha_-22.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 024" },
    { src: "photos/gourmet/gourmet_hyogensha_-24.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 025" },
    { src: "photos/gourmet/gourmet_hyogensha_-26.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 026" },
    { src: "photos/gourmet/gourmet_hyogensha_-27.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 027" },
    { src: "photos/gourmet/gourmet_hyogensha_-28.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 028" },
    { src: "photos/gourmet/gourmet_hyogensha_-29.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 029" },
    { src: "photos/gourmet/gourmet_hyogensha_-3.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 030" },
    { src: "photos/gourmet/gourmet_hyogensha_-30.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 031" },
    { src: "photos/gourmet/gourmet_hyogensha_-32.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 032" },
    { src: "photos/gourmet/gourmet_hyogensha_-33.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 033" },
    { src: "photos/gourmet/gourmet_hyogensha_-34.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 034" },
    { src: "photos/gourmet/gourmet_hyogensha_-35.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 035" },
    { src: "photos/gourmet/gourmet_hyogensha_-37.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 036" },
    { src: "photos/gourmet/gourmet_hyogensha_-38.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 037" },
    { src: "photos/gourmet/gourmet_hyogensha_-39.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 038" },
    { src: "photos/gourmet/gourmet_hyogensha_-4.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 039" },
    { src: "photos/gourmet/gourmet_hyogensha_-43.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 040" },
    { src: "photos/gourmet/gourmet_hyogensha_-44.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 041" },
    { src: "photos/gourmet/gourmet_hyogensha_-45.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 042" },
    { src: "photos/gourmet/gourmet_hyogensha_-46.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 043" },
    { src: "photos/gourmet/gourmet_hyogensha_-47.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 044" },
    { src: "photos/gourmet/gourmet_hyogensha_-48.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 045" },
    { src: "photos/gourmet/gourmet_hyogensha_-49.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 046" },
    { src: "photos/gourmet/gourmet_hyogensha_-5.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 047" },
    { src: "photos/gourmet/gourmet_hyogensha_-50.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 048" },
    { src: "photos/gourmet/gourmet_hyogensha_-51.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 049" },
    { src: "photos/gourmet/gourmet_hyogensha_-54.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 050" },
    { src: "photos/gourmet/gourmet_hyogensha_-56.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 051" },
    { src: "photos/gourmet/gourmet_hyogensha_-57.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 052" },
    { src: "photos/gourmet/gourmet_hyogensha_-58.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 053" },
    { src: "photos/gourmet/gourmet_hyogensha_-59.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 054" },
    { src: "photos/gourmet/gourmet_hyogensha_-6.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 055" },
    { src: "photos/gourmet/gourmet_hyogensha_-60.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 056" },
    { src: "photos/gourmet/gourmet_hyogensha_-61.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 057" },
    { src: "photos/gourmet/gourmet_hyogensha_-62.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 058" },
    { src: "photos/gourmet/gourmet_hyogensha_-63.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 059" },
    { src: "photos/gourmet/gourmet_hyogensha_-64.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 060" },
    { src: "photos/gourmet/gourmet_hyogensha_-65.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 061" },
    { src: "photos/gourmet/gourmet_hyogensha_-66.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 062" },
    { src: "photos/gourmet/gourmet_hyogensha_-67.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 063" },
    { src: "photos/gourmet/gourmet_hyogensha_-68.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 064" },
    { src: "photos/gourmet/gourmet_hyogensha_-69.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 065" },
    { src: "photos/gourmet/gourmet_hyogensha_-7.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 066" },
    { src: "photos/gourmet/gourmet_hyogensha_-71.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 067" },
    { src: "photos/gourmet/gourmet_hyogensha_-72.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 068" },
    { src: "photos/gourmet/gourmet_hyogensha_-73.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 069" },
    { src: "photos/gourmet/gourmet_hyogensha_-8.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 070" },
    { src: "photos/gourmet/gourmet_hyogensha_-9.jpg", alt: "HAYATO KITAMURA 作品｜グルメ写真 071" }
  ],
  sweets: [
    { src: "photos/sweets/gourmet_hyogensha_-40.jpg", alt: "HAYATO KITAMURA 作品｜スイーツ写真 001" },
    { src: "photos/sweets/gourmet_hyogensha_-41.jpg", alt: "HAYATO KITAMURA 作品｜スイーツ写真 002" }
  ]
};
