/* =========================================================
   ★ 写真の差し替えはこのファイルだけ編集すればOK ★

   ■ 写真を差し替える
     photos/hero/ や photos/gallery/ フォルダに写真を入れ、
     下のリストのファイル名を書き換える。

   ■ 並び順を変える
     行を上下に入れ替えるだけ。上にある写真が先に表示される。

   ■ 写真を増やす・減らす
     行をコピーして追加、または行を削除。

   ※ hero は横長写真（トップのスライドショー用）
   ※ gallery は縦横どちらでもOK（自動でグリッドに並ぶ）
   ========================================================= */

const SITE_PHOTOS = {

  /* --- トップのスライドショー（横長写真） --- */
  hero: [
    { src: "photos/hero/_65A2451-1.jpg", alt: "HAYATO KITAMURA 作品｜高級スイーツの質感を捉えた写真" },
    { src: "photos/hero/_V5A2029-1.jpg", alt: "HAYATO KITAMURA 作品｜レストランのグルメ写真" },
    { src: "photos/hero/_V5A7737-1.jpg", alt: "HAYATO KITAMURA 作品｜高級スイーツの質感を捉えた写真" },
  ],

  /* --- グリッドギャラリー（縦横バラバラでOK） --- */
  gallery: [
    { src: "photos/gallery/0001.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 001" },
    { src: "photos/gallery/0008.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 002" },
    { src: "photos/gallery/3I5A0288-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 003" },
    { src: "photos/gallery/3I5A1010-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 004" },
    { src: "photos/gallery/3I5A2996-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 005" },
    { src: "photos/gallery/3I5A3063-f2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 006" },
    { src: "photos/gallery/3I5A4221-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 007" },
    { src: "photos/gallery/3I5A4773-2.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 008" },
    { src: "photos/gallery/3I5A5109-2.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 009" },
    { src: "photos/gallery/A1-2.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 010" },
    { src: "photos/gallery/A1-4.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 011" },
    { src: "photos/gallery/A2-3.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 012" },
    { src: "photos/gallery/A2-5.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 013" },
    { src: "photos/gallery/A2-7.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 014" },
    { src: "photos/gallery/A3-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 015" },
    { src: "photos/gallery/A3-14.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 016" },
    { src: "photos/gallery/A3-15.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 017" },
    { src: "photos/gallery/A3-18.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 018" },
    { src: "photos/gallery/A4-18.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 019" },
    { src: "photos/gallery/A4-25.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 020" },
    { src: "photos/gallery/A4-30.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 021" },
    { src: "photos/gallery/A4-31.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 022" },
    { src: "photos/gallery/A4-37.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 023" },
    { src: "photos/gallery/A4-4.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 024" },
    { src: "photos/gallery/_65A0058-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 025" },
    { src: "photos/gallery/_65A0130-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 026" },
    { src: "photos/gallery/_65A0169-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 027" },
    { src: "photos/gallery/_65A0172-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 028" },
    { src: "photos/gallery/_65A0181-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 029" },
    { src: "photos/gallery/_65A0237-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 030" },
    { src: "photos/gallery/_65A0254-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 031" },
    { src: "photos/gallery/_65A0798-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 032" },
    { src: "photos/gallery/_65A1258-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 033" },
    { src: "photos/gallery/_65A1632-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 034" },
    { src: "photos/gallery/_65A2420-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 035" },
    { src: "photos/gallery/_65A2806-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 036" },
    { src: "photos/gallery/_65A3434-1-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 037" },
    { src: "photos/gallery/_65A3751-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 038" },
    { src: "photos/gallery/_65A3973-1加工したら絵になる.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 039" },
    { src: "photos/gallery/_65A4014-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 040" },
    { src: "photos/gallery/_65A5005-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 041" },
    { src: "photos/gallery/_65A5769-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 042" },
    { src: "photos/gallery/_65A6940-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 043" },
    { src: "photos/gallery/_65A7896-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 044" },
    { src: "photos/gallery/_65A8145-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 045" },
    { src: "photos/gallery/_65A8247-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 046" },
    { src: "photos/gallery/_65A8599-強化-NR.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 047" },
    { src: "photos/gallery/_65A9105-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 048" },
    { src: "photos/gallery/_65A9202-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 049" },
    { src: "photos/gallery/_65A9328-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 050" },
    { src: "photos/gallery/_65A9419-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 051" },
    { src: "photos/gallery/_65A9425-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 052" },
    { src: "photos/gallery/_65A9434-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 053" },
    { src: "photos/gallery/_65A9544-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 054" },
    { src: "photos/gallery/_65A9572-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 055" },
    { src: "photos/gallery/_65A9618-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 056" },
    { src: "photos/gallery/_65A9724-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 057" },
    { src: "photos/gallery/_65A9739-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 058" },
    { src: "photos/gallery/_65A9809-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 059" },
    { src: "photos/gallery/_I5A0336-強化-NR-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 060" },
    { src: "photos/gallery/_I5A0408-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 061" },
    { src: "photos/gallery/_I5A0421-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 062" },
    { src: "photos/gallery/_I5A0546-強化-NR-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 063" },
    { src: "photos/gallery/_I5A1176-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 064" },
    { src: "photos/gallery/_I5A1306-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 065" },
    { src: "photos/gallery/_I5A1313-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 066" },
    { src: "photos/gallery/_I5A1350-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 067" },
    { src: "photos/gallery/_I5A1375-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 068" },
    { src: "photos/gallery/_I5A2482-強化-NR-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 069" },
    { src: "photos/gallery/_I5A2493-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 070" },
    { src: "photos/gallery/_I5A2685-強化-NR-1-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 071" },
    { src: "photos/gallery/_I5A2895-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 072" },
    { src: "photos/gallery/_I5A2946-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 073" },
    { src: "photos/gallery/_I5A2989-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 074" },
    { src: "photos/gallery/_I5A3227-強化-NR-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 075" },
    { src: "photos/gallery/_I5A3354-強化-NR-1-c.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 076" },
    { src: "photos/gallery/_I5A3382-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 077" },
    { src: "photos/gallery/_I5A3734-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 078" },
    { src: "photos/gallery/_I5A4210-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 079" },
    { src: "photos/gallery/_I5A4236-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 080" },
    { src: "photos/gallery/_I5A4244-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 081" },
    { src: "photos/gallery/_I5A4444-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 082" },
    { src: "photos/gallery/_I5A4466-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 083" },
    { src: "photos/gallery/_I5A4751-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 084" },
    { src: "photos/gallery/_I5A4783-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 085" },
    { src: "photos/gallery/_I5A4788-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 086" },
    { src: "photos/gallery/_I5A4790-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 087" },
    { src: "photos/gallery/_I5A4858-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 088" },
    { src: "photos/gallery/_I5A4974-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 089" },
    { src: "photos/gallery/_I5A5056-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 090" },
    { src: "photos/gallery/_I5A5070-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 091" },
    { src: "photos/gallery/_I5A5080-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 092" },
    { src: "photos/gallery/_I5A5086-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 093" },
    { src: "photos/gallery/_I5A5877-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 094" },
    { src: "photos/gallery/_I5A5889-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 095" },
    { src: "photos/gallery/_I5A5898-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 096" },
    { src: "photos/gallery/_I5A6024-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 097" },
    { src: "photos/gallery/_I5A6028-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 098" },
    { src: "photos/gallery/_I5A6047-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 099" },
    { src: "photos/gallery/_I5A6273-1-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 100" },
    { src: "photos/gallery/_I5A6277-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 101" },
    { src: "photos/gallery/_I5A6288-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 102" },
    { src: "photos/gallery/_I5A6494-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 103" },
    { src: "photos/gallery/_I5A6498-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 104" },
    { src: "photos/gallery/_I5A6527-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 105" },
    { src: "photos/gallery/_I5A6570-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 106" },
    { src: "photos/gallery/_I5A7401-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 107" },
    { src: "photos/gallery/_I5A7423-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 108" },
    { src: "photos/gallery/_I5A7521-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 109" },
    { src: "photos/gallery/_I5A7530-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 110" },
    { src: "photos/gallery/_I5A7640-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 111" },
    { src: "photos/gallery/_I5A8781-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 112" },
    { src: "photos/gallery/_I5A8864-強化-NR-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 113" },
    { src: "photos/gallery/_I5A8911-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 114" },
    { src: "photos/gallery/_I5A9158-強化-NR-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 115" },
    { src: "photos/gallery/_I5A9716-1-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 116" },
    { src: "photos/gallery/_I5A9747-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 117" },
    { src: "photos/gallery/_V5A1331-b1-2-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 118" },
    { src: "photos/gallery/_V5A1347-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 119" },
    { src: "photos/gallery/_V5A1530-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 120" },
    { src: "photos/gallery/_V5A3498-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 121" },
    { src: "photos/gallery/_V5A3507-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 122" },
    { src: "photos/gallery/_V5A4858-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 123" },
    { src: "photos/gallery/_V5A5419-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 124" },
    { src: "photos/gallery/_V5A6857-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 125" },
    { src: "photos/gallery/_V5A7837-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 126" },
    { src: "photos/gallery/_V5A8657-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 127" },
    { src: "photos/gallery/バブカ-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 128" },
  ],

  /* --- 横位置（landscape）の写真だけをまとめた行 ---
     ここに入れた写真は、縦グリッドとは別に横長のまま1カ所にまとめて表示されます */
  galleryWide: [
    { src: "photos/gallery/_65A2451-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 129" },
    { src: "photos/gallery/_V5A1543-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 130" },
    { src: "photos/gallery/A3-23.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 131" },
    { src: "photos/gallery/_65A0032-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 132" },
    { src: "photos/gallery/_V5A7772.JPG", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 133" },
    { src: "photos/gallery/_V5A8728-1.jpg", alt: "HAYATO KITAMURA 作品｜グルメ・スイーツ写真 134" },
  ],

};
