/* =========================================================
   ★ 写真の差し替えはこのファイルだけ編集すればOK ★

   ■ 写真を差し替える
     photos/hero/ や photos/gallery/ フォルダに写真を入れ、
     下のリストのファイル名を書き換える。

   ■ 並び順を変える
     行を上下に入れ替えるだけ。上にある写真が先に表示される。

   ■ 写真を増やす・減らす
     行をコピーして追加、または行を削除。

   ※ hero は横長写真（トップのスライドショー用）
   ※ gallery は縦横どちらでもOK（自動でグリッドに並ぶ）
   ========================================================= */

const SITE_PHOTOS = {

  /* --- トップのスライドショー（横長写真） --- */
  hero: [
    { src: "photos/hero/_65A2451-1.jpg", alt: "スイーツ写真" },
    { src: "photos/hero/_V5A2029-1.jpg", alt: "グルメ写真" },
    { src: "photos/hero/_V5A7737-1.jpg", alt: "スイーツ写真" },
  ],

  /* --- グリッドギャラリー（縦横バラバラでOK） --- */
  gallery: [
    { src: "photos/gallery/0001.jpg", alt: "作品" },
    { src: "photos/gallery/0008.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A0288-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A1010-1.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A2996-1.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A3063-f2-1.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A4221-1.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A4773-2.jpg", alt: "作品" },
    { src: "photos/gallery/3I5A5109-2.jpg", alt: "作品" },
    { src: "photos/gallery/A1-2.JPG", alt: "作品" },
    { src: "photos/gallery/A1-4.jpg", alt: "作品" },
    { src: "photos/gallery/A2-3.jpg", alt: "作品" },
    { src: "photos/gallery/A2-5.jpg", alt: "作品" },
    { src: "photos/gallery/A2-7.jpg", alt: "作品" },
    { src: "photos/gallery/A3-1.jpg", alt: "作品" },
    { src: "photos/gallery/A3-14.JPG", alt: "作品" },
    { src: "photos/gallery/A3-15.JPG", alt: "作品" },
    { src: "photos/gallery/A3-18.JPG", alt: "作品" },
    { src: "photos/gallery/A4-18.jpg", alt: "作品" },
    { src: "photos/gallery/A4-25.JPG", alt: "作品" },
    { src: "photos/gallery/A4-30.jpg", alt: "作品" },
    { src: "photos/gallery/A4-31.jpg", alt: "作品" },
    { src: "photos/gallery/A4-37.jpg", alt: "作品" },
    { src: "photos/gallery/A4-4.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0058-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0130-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0169-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0172-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0181-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0237-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0254-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A0798-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A1258-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A1632-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A2420-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A2806-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A3434-1-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A3751-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A3973-1加工したら絵になる.jpg", alt: "作品" },
    { src: "photos/gallery/_65A4014-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A5005-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A5769-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A6940-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A7896-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A8145-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A8247-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A8599-強化-NR.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9105-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9202-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9328-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9419-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9425-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9434-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9544-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9572-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9618-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9724-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9739-1.jpg", alt: "作品" },
    { src: "photos/gallery/_65A9809-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A0336-強化-NR-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A0408-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A0421-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A0546-強化-NR-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A1176-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A1306-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A1313-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A1350-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A1375-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2482-強化-NR-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2493-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2685-強化-NR-1-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2895-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2946-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A2989-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A3227-強化-NR-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A3354-強化-NR-1-c.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A3382-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A3734-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4210-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4236-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4244-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4444-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4466-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4751-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4783-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4788-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4790-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4858-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A4974-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5056-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5070-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5080-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5086-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5877-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5889-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A5898-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6024-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6028-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6047-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6273-1-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6277-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6288-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6494-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6498-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6527-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A6570-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A7401-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A7423-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A7521-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A7530-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A7640-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A8781-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A8864-強化-NR-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A8911-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A9158-強化-NR-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A9716-1-1.jpg", alt: "作品" },
    { src: "photos/gallery/_I5A9747-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A1331-b1-2-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A1347-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A1530-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A3498-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A3507-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A4858-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A5419-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A6857-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A7837-1.jpg", alt: "作品" },
    { src: "photos/gallery/_V5A8657-1.jpg", alt: "作品" },
    { src: "photos/gallery/バブカ-1.jpg", alt: "作品" },
  ],

  /* --- 横位置（landscape）の写真だけをまとめた行 ---
     ここに入れた写真は、縦グリッドとは別に横長のまま1カ所にまとめて表示されます */
  galleryWide: [
    { src: "photos/gallery/_65A2451-1.jpg", alt: "作品（横位置）" },
    { src: "photos/gallery/_V5A1543-1.jpg", alt: "作品（横位置）" },
    { src: "photos/gallery/A3-23.jpg", alt: "作品（横位置）" },
    { src: "photos/gallery/_65A0032-1.jpg", alt: "作品（横位置）" },
    { src: "photos/gallery/_V5A7772.JPG", alt: "作品（横位置）" },
    { src: "photos/gallery/_V5A8728-1.jpg", alt: "作品（横位置）" },
  ],

};
